version: '3.8'
services:
  backend:
    build:
      context: ../backend
      dockerfile: ../docker/Dockerfile.backend
    ports:
      - "8080:8080"
    depends_on:
      - db
  frontend:
    build:
      context: ../frontend/commercial-offer-frontend
      dockerfile: ../docker/Dockerfile.frontend
    ports:
      - "3000:3000"
  db:
    image: nouchka/sqlite3:latest
    volumes:
      - ../backend/commercial_offer.db:/commercial_offer.db